using Test

@testset "UTDKernels.jl" begin
    include("test_finite_edge.jl")
    include("test_wedge_face_edge.jl")
    include("test_transition_passive.jl")
    include("test_transition_bivariate.jl")
    include("test_curvature_measure.jl")
    include("test_transition_multipole.jl")
    include("test_hessian_metric.jl")
    include("test_null_uniform_moments.jl")
    include("test_transition.jl")
    include("test_regimes.jl")
    include("test_wedge_pec_continuity.jl")
    include("test_wedge_pec_generalized_L.jl")
    include("test_wedge_pec_infinite_L.jl")
    include("test_wedge_pec_limits.jl")
    include("test_wedge_pec_grazing.jl")
    include("test_interior_wedge.jl")
    include("test_symmetry.jl")
    include("test_ad.jl")
    include("test_wedge_impedance.jl")
    include("test_reference_values.jl")
    include("test_maliuzhinets.jl")
    include("test_robustness.jl")
    include("test_validation_harness.jl")
end
